# Generated by Django 2.0 on 2017-12-29 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('8e04155d-294e-414d-88cd-9f085172040b'), primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('13bf1dbf-30f5-4ef3-bbba-7270e525bd88'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('access_code', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=200)),
                ('shares', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('153d0f46-0012-4d08-a815-602380146d64'), primary_key=True, serialize=False)),
                ('ticker', models.TextField(max_length=3)),
                ('unit_value', models.FloatField()),
                ('value_last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DollarDeposit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('591bdda7-d3c4-4cac-a988-205d75bd20ce'), primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Client')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Currency'),
        ),
    ]
