# Generated by Django 2.0 on 2017-12-29 03:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a71003bf-cbe1-4bd8-8fb3-98b063221acc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d3619c9d-6596-49e4-a9b6-7235cdb880c3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='unit_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('22970a30-80e2-4824-b8dc-7858bb88f92e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='value_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dollardeposit',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6baabf9c-4e77-4940-b154-efec205fb5f6'), primary_key=True, serialize=False),
        ),
    ]
