# Generated by Django 2.0 on 2017-12-29 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20171229_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d253e757-e42a-4f91-8afb-3dc09da03f48'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('63b58def-623f-4e9c-b448-05a2432352fa'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='unit_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aa31f4a1-f8a1-43c7-aca1-3c7a22d84367'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='value_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollardeposit',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('78454214-1a8c-429c-8b21-d3c65d3746a9'), primary_key=True, serialize=False),
        ),
    ]
